<?php
header('Content-Type: application/json');
// Tu JSON como array PHP
$response = [
    "status"=> "success",
    "alumno"=> [
        "nombre"=>"Alfonsina",
        "apellido"=>"Abregu Alvarez",
        "curso"=>"3",
        "division"=>"A",
        "ciclo"=>"INI"
    ],
    "materias"=> [
        "materia_id"=> [
            "17Z3",
            "12Z3",
            "21Z3",
            "43Z3",
            "16Z3",
            "19Z3",
            "31Z3",
            "47Z3",
            "42Z3",
            "45Z3",
            "22Z3",
            "39Z3",
            "32Z3",
            "11Z3",
            "44Z3",
            "20Z3",
            "13Z3",
            "46Z3",
            "30Z3",
            "23Z3",
            "33Z3",
            "14Z3",
            "25Z3",
            "37Z3",
            "18Z3",
            "38Z3",
            "48Z3",
            "35Z3",
            "26Z3",
            "34Z3",
            "28Z3",
            "29Z3",
            "24Z3",
            "27Z3",
            "36Z3",
            "10Z3",
            "15Z3",
            "40Z3",
            "41Z3"
        ],
        "nombre_materia_primaria"=> [
            "Amplia su vocabulario de uso cotidiano (nominaciòn de personas, animales, objetos familiares,etc)",
            "Comprende las consignas simples de trabajo",
            "Cuida el ambiente natural (animales, plantas, agua).",
            "Desarrolla hábitos relacionados con el cuidado de sí mismo",
            "Describe imágenes sencillas",
            "Disfruta de la lectura y narración",
            "Explora y observa los materiales y juguetes.",
            "Explora, manipula elementos convencionales y no convencionales (pelota, aro, soga,etc)",
            "Identifica las partes de su cuerpo y nombra sus partes externas.",
            "Identifica los diferentes espacios y momentos de oración, reconociendo los elementos propios de la Meditacion Cristiana",
            "Identifica y reconoce carcteristicas de algunos seres vivos (animales, plantas)",
            "Interactúa con sus pares a través del gesto, el contacto, la mirada, el movimiento, y el juego",
            "Interpreta las consignas de juego",
            "Muestra autonomia en las actividades que realiza en la sala (higiene, desayuno, guardar sus pertenencias, entre otros)",
            "Participa activamente de la propuesta pedagógica del Taller de Espiritualidad",
            "Participa activamente en rondas de intercambio (conversación, diálogo espontáneo y narraciones de la vida cotidiana)",
            "Participa de la construcción de acuerdos de convivencia, a partir del diálogo de situaciones cotidianas.",
            "Participa de manera rítmica y vocal coordinando destrezas corporales",
            "Participa en difernetes formatos de juego. (dramático, simbólico, libre, de construcciòn)",
            "Participa en la observación y registro de la información a través de dibujos.",
            "Participa en la organización de los materiales y del espacio",
            "Posee un vocabulario acorde a su edad",
            "Realiza conteo hasta el 5",
            "Realiza el dibujo del garabato controlado",
            "Realiza imitaciones sono-lúdicas del lenguaje: onomatopeyas, exclamaciones, entonación",
            "Realiza movimientos corporales al escuchar melodías de diferentes estilos",
            "Realiza prácticas locomotivas como: caminar, correr, saltar y no locomotivas: treparse",
            "Realiza producciones grafo-pláticas con diversos materiales: fibras, tizas en almibar, masa de sal, plasticola , etc",
            "Realiza seriaciones simples",
            "Reconoce colores",
            "Reconoce el uso de la medida no convencional en situaciones cotidianas",
            "Reconoce figuras geométricas mediante la exploración",
            "Reconoce números",
            "Reconoce relaciones espaciales (arriba-abajo, cerca-lejos, adentro-afuera)",
            "Representa formas bidimensionales y tridimnesionales: dibuja, pinta, modela",
            "Responde a su nombre",
            "Se expresa de manera oral por sobre el gestual",
            "Usa diferentes objetos para el movimiento libre",
            "Utiliza y explora objetos inanimados (titeres, muñecos de apegos, etc) y los recrea para jugar"
        ]
    ],
    "calificaciones"=> [
        "CU1"=> [
            "10Z3"=> "6",
            "11Z3"=> "6",
            "12Z3"=> "6",
            "13Z3"=> "6",
            "14Z3"=> "5",
            "15Z3"=> "6",
            "16Z3"=> "6",
            "17Z3"=> "6",
            "18Z3"=> "6",
            "19Z3"=> "6",
            "20Z3"=> "6",
            "23Z3"=> "5",
            "24Z3"=> "6",
            "25Z3"=> "6",
            "26Z3"=> "5",
            "27Z3"=> "5",
            "30Z3"=> "6",
            "31Z3"=> "6",
            "32Z3"=> "5",
            "33Z3"=> "6",
            "34Z3"=> "6",
            "35Z3"=> "6",
            "36Z3"=> "6",
            "37Z3"=> "6",
            "38Z3"=> "6",
            "39Z3"=> "6",
            "40Z3"=> "6",
            "41Z3"=> "6",
            "42Z3"=> "6",
            "43Z3"=> "6",
            "44Z3"=> "6",
            "45Z3"=> "5",
            "46Z3"=> "6",
            "47Z3"=> "6",
            "48Z3"=> "6"
    ]
    ,
        "CU2"=> [
            "10Z3"=> "6",
            "11Z3"=> "6",
            "12Z3"=> "6",
            "13Z3"=> "6",
            "14Z3"=> "6",
            "15Z3"=> "6",
            "16Z3"=> "6",
            "17Z3"=> "6",
            "18Z3"=> "6",
            "19Z3"=> "6",
            "20Z3"=> "6",
            "21Z3"=> "6",
            "22Z3"=> "6",
            "23Z3"=> "6",
            "24Z3"=> "6",
            "25Z3"=> "6",
            "26Z3"=> "6",
            "27Z3"=> "6",
            "28Z3"=> "6",
            "29Z3"=> "6",
            "30Z3"=> "6",
            "31Z3"=> "6",
            "32Z3"=> "6",
            "33Z3"=> "6",
            "34Z3"=> "6",
            "35Z3"=> "6",
            "36Z3"=> "6",
            "37Z3"=> "6",
            "38Z3"=> "6",
            "39Z3"=> "6",
            "40Z3"=> "6",
            "41Z3"=> "6",
            "42Z3"=> "6",
            "43Z3"=> "6",
            "44Z3"=> "6",
            "45Z3"=> "6",
            "46Z3"=> "6",
            "47Z3"=> "6",
            "48Z3"=> "6"
        ]
    ],
    "observaciones"=> [
        "tr1"=> null,
        "tr2"=> null,
        "tr3"=> null
    ],
    "asistencias"=> [
        "LTI"=> 0,
        "LTJ"=> 0,
        "EFI"=> 0,
        "EFJ"=> 0,
        "injus"=> null,
        "jus"=> null,
        "tot"=> 7,
        "pre"=> null,
        "pretot"=> 166,
        "preTR1"=> 58,
        "preTR2"=> 54,
        "preTR3"=> 50,
        "injusTR1"=> 0,
        "injusTR2"=> 0,
        "injusTR3"=> 6,
        "jusTR1"=> 0,
        "jusTR2"=> 0,
        "jusTR3"=> 0,
        "injustot"=> 7,
        "justot"=> null,
        "LTITR1"=> 0,
        "LTITR2"=> 0,
        "LTITR3"=> 0,
        "LTJTR1"=> 0,
        "LTJTR2"=> 0,
        "LTJTR3"=> 0,
        "EFITR1"=> 0,
        "EFITR2"=> 0,
        "EFITR3"=> 0,
        "EFJTR1"=> 0,
        "EFJTR2"=> 0,
        "EFJTR3"=> 0
    ]
];
$respose_sec =[
    "status"=> "success",
    "alumno"=> [
        "nombre"=> "Sofia Constanza",
        "apellido"=> "Acosta Garcia",
        "curso"=> "1",
        "division"=> "A",
        "ciclo"=> "SEC"
    ],
    "materias"=> [
        "materia_id"=> [
            "BIE7",
            "DIE7",
            "EAE7",
            "EFE7",
            "FQE7",
            "CAE7",
            "GEE7",
            "HIE7",
            "LEE7",
            "IAE7",
            "MAE7",
            "TIE7",
            "TTE7",
            "ITE7",
            "TUE7"
        ],
        "nombre_materia_primaria"=> [
            "Biología",
            "EDI=> Literatura Inglesa Infanto Juvenil A",
            "Educación Artística",
            "Educación Física",
            "Físico-Química",
            "Formación Moral\/Religión (Carisma Dominicano)",
            "Geografía",
            "Historia",
            "Lengua",
            "Lengua Extranjera A",
            "Matemáticas",
            "Taller=> Informática",
            "Taller=> Técnicas de Trabajo Intelectual",
            "Tecnología",
            "Tutoría"
        ]
    ],
    "calificaciones"=> [
        "IC3"=> [
            "BIE7"=> "7",
            "FQE7"=> "6",
            "HIE7"=> null,
            "MAE7"=> "1"
        ],
        "N41"=> [
            "BIE7"=> "2",
            "CAE7"=> "0",
            "DIE7"=> "0",
            "EAE7"=> "1",
            "EFE7"=> "1",
            "FQE7"=> "0",
            "GEE7"=> "0",
            "HIE7"=> "1",
            "IAE7"=> "6",
            "ITE7"=> "0",
            "LEE7"=> "4",
            "MAE7"=> "0",
            "TIE7"=> "0",
            "TTE7"=> "0",
            "TUE7"=> "2"
        ],
        "N42"=> [
            "BIE7"=> "1",
            "CAE7"=> "0",
            "DIE7"=> "2",
            "EAE7"=> "0",
            "EFE7"=> "0",
            "FQE7"=> "2",
            "GEE7"=> "2",
            "HIE7"=> "1",
            "IAE7"=> "2",
            "ITE7"=> "1",
            "LEE7"=> "0",
            "MAE7"=> "0",
            "TIE7"=> "0",
            "TUE7"=> "0"
        ],
        "N43"=> [
            "BIE7"=> "0",
            "CAE7"=> "0",
            "DIE7"=> "0",
            "EAE7"=> "0",
            "EFE7"=> "0",
            "FQE7"=> "0",
            "GEE7"=> "0",
            "HIE7"=> "0",
            "IAE7"=> "0",
            "LEE7"=> "0",
            "MAE7"=> "0",
            "TIE7"=> "0",
            "TTE7"=> "0",
            "TUE7"=> "0"
        ],
        "TR1"=> [
            "BIE7"=> "6",
            "CAE7"=> "8",
            "DIE7"=> "10",
            "EAE7"=> "8",
            "EFE7"=> "8",
            "FQE7"=> "6",
            "GEE7"=> "4",
            "HIE7"=> "4",
            "IAE7"=> "6",
            "ITE7"=> "5",
            "LEE7"=> "3",
            "MAE7"=> "1",
            "TIE7"=> "6",
            "TTE7"=> "7",
            "TUE7"=> "B"
        ],
        "TR2"=> [
            "BIE7"=> "8",
            "CAE7"=> "6",
            "DIE7"=> "8",
            "EAE7"=> "8",
            "EFE7"=> "10",
            "FQE7"=> "4",
            "GEE7"=> "2",
            "HIE7"=> "4",
            "IAE7"=> "7",
            "ITE7"=> "7",
            "LEE7"=> "8",
            "MAE7"=> "2",
            "TIE7"=> "7",
            "TTE7"=> "6",
            "TUE7"=> "MB"
        ],
        "TR3"=> [
            "BIE7"=> "4",
            "CAE7"=> "6",
            "DIE7"=> "10",
            "EAE7"=> "8",
            "EFE7"=> "9",
            "FQE7"=> "5",
            "GEE7"=> "10",
            "HIE7"=> "8",
            "IAE7"=> "6",
            "ITE7"=> "8",
            "LEE7"=> "7",
            "MAE7"=> "3",
            "TIE7"=> "9",
            "TTE7"=> "9",
            "TUE7"=> "EX"
        ],
        "IC2"=> [
            "FQE7"=> "3",
            "GEE7"=> "2",
            "HIE7"=> "4",
            "MAE7"=> "6"
        ],
        "IC1"=> [
            "GEE7"=> "4",
            "HIE7"=> "6",
            "ITE7"=> "7",
            "LEE7"=> "6",
            "MAE7"=> "6"
        ]
    ],
    "observaciones"=> [
        "tr1"=> [
            "legajo"=> "51226554",
            "anio"=> "2024",
            "ciclo_id"=> "SEC",
            "eval_id"=> "TR1",
            "compor_con"=> "B",
            "compor_obs"=> "",
            "puntua_con"=> null,
            "puntua_obs"=> "",
            "presen_con"=> "MB",
            "presen_obs"=> "",
            "observ_obs"=> null,
            "ausent_jus"=> null,
            "ausent_inj"=> null,
            "ausent_lta"=> null,
            "ausent_edf"=> null,
            "reinco_obs"=> null,
            "asistp_1"=> null,
            "asistp_2"=> null,
            "asistp_3"=> null,
            "adverten_obs"=> null,
            "mainobs_obs"=> null,
            "tallerobs_obs"=> null,
            "habito_con"=> "",
            "trabaj_con"=> null,
            "partic_con"=> null,
            "vinculo_con"=> null
        ],
        "tr2"=> [
            "legajo"=> "51226554",
            "anio"=> "2024",
            "ciclo_id"=> "SEC",
            "eval_id"=> "TR2",
            "compor_con"=> "MB",
            "compor_obs"=> "0",
            "puntua_con"=> "NUL",
            "puntua_obs"=> "0",
            "presen_con"=> "MB",
            "presen_obs"=> "0",
            "observ_obs"=> "",
            "ausent_jus"=> "0.0",
            "ausent_inj"=> "0.0",
            "ausent_lta"=> "0",
            "ausent_edf"=> "0",
            "reinco_obs"=> null,
            "asistp_1"=> "",
            "asistp_2"=> "",
            "asistp_3"=> null,
            "adverten_obs"=> null,
            "mainobs_obs"=> null,
            "tallerobs_obs"=> null,
            "habito_con"=> "0",
            "trabaj_con"=> "NUL",
            "partic_con"=> "NUL",
            "vinculo_con"=> "NUL"
        ],
        "tr3"=> [
            "legajo"=> "51226554",
            "anio"=> "2024",
            "ciclo_id"=> "SEC",
            "eval_id"=> "TR3",
            "compor_con"=> "MB",
            "compor_obs"=> "",
            "puntua_con"=> null,
            "puntua_obs"=> "",
            "presen_con"=> "MB",
            "presen_obs"=> "",
            "observ_obs"=> null,
            "ausent_jus"=> null,
            "ausent_inj"=> null,
            "ausent_lta"=> null,
            "ausent_edf"=> null,
            "reinco_obs"=> null,
            "asistp_1"=> null,
            "asistp_2"=> null,
            "asistp_3"=> null,
            "adverten_obs"=> null,
            "mainobs_obs"=> null,
            "tallerobs_obs"=> null,
            "habito_con"=> "",
            "trabaj_con"=> null,
            "partic_con"=> null,
            "vinculo_con"=> null
        ]
    ],
    "asistencias"=> [
        "LTI"=> 0,
        "LTJ"=> 0,
        "EFI"=> 0,
        "EFJ"=> 0,
        "injus"=> null,
        "jus"=> null,
        "tot"=> 5,
        "pre"=> null,
        "pretot"=> 165,
        "preTR1"=> 54,
        "preTR2"=> 52,
        "preTR3"=> 54,
        "injusTR1"=> 1,
        "injusTR2"=> 1,
        "injusTR3"=> 0,
        "jusTR1"=> 2,
        "jusTR2"=> 0,
        "jusTR3"=> 0,
        "injustot"=> 3,
        "justot"=> 2,
        "LTITR1"=> 0,
        "LTITR2"=> 0,
        "LTITR3"=> 0,
        "LTJTR1"=> 0,
        "LTJTR2"=> 0,
        "LTJTR3"=> 0,
        "EFITR1"=> 0,
        "EFITR2"=> 0,
        "EFITR3"=> 0,
        "EFJTR1"=> 0,
        "EFJTR2"=> 0,
        "EFJTR3"=> 0
    ]
];

$dni = $_GET['dni'] ?? '';

$alumnos = [
    '51226554' => $respose_sec,
    '12345678' => $response
];

if (isset($alumnos[$dni])) {
    echo json_encode($alumnos[$dni]);
} else {
    echo json_encode(['status' => 'error', 'message' => 'Alumno no encontrado']);
}
?>